// model_to_header.cpp
//
// Standalone HOST tool compiled and run on my dev machine with the
// normal system g++/libstdc++, NOT part of Rock OS itself. It reads the
// same binary layout ModelIO::save() writes and emits a self-contained
// C++ header containing every weight as a constexpr float array, so
// Rock OS can embed the trained model directly into its own binary and
// never needs to open a file, have a filesystem, or link against
// <fstream> at runtime.
//
// Usage:
//   ./model_to_header rock_ai.model rock_ai_weights.hpp [array_name]
//
// array_name defaults to ROCK_AI_WEIGHTS if omitted.

#include <cctype>
#include <cstdint>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <limits>
#include <string>
#include <vector>

namespace {

// Must stay byte-for-byte identical to ModelIO::Header in model_io.hpp.
// This tool reads the exact same file format that class writes.
struct Header {
  uint32_t magic;
  uint32_t version;
  uint32_t vocabulary_size;
  uint32_t layer_count;
  uint32_t parameter_count;
};

constexpr uint32_t EXPECTED_MAGIC = 0x524F434B;
constexpr uint32_t EXPECTED_VERSION = 1;

// Uppercases and replaces anything that isn't [A-Z0-9_] with '_', so a
// user-supplied array name is always safe to drop straight into a C++
// header.
std::string sanitize_identifier(const std::string &raw) {
  std::string out;
  out.reserve(raw.size());

  for (char c : raw) {
    if ((c >= 'a' && c <= 'z') ||
        (c >= 'A' && c <= 'Z') ||
        (c >= '0' && c <= '9') ||
        c == '_') {

      out.push_back(
          static_cast<char>(
              std::toupper(static_cast<unsigned char>(c))));

    } else {
      out.push_back('_');
    }
  }

  if (out.empty() ||
      (out[0] >= '0' && out[0] <= '9')) {

    out = "_" + out;
  }

  return out;
}

// Writes a float as valid C++ source while preserving enough precision
// for an exact float32 round-trip.
void write_float_literal(std::ostream &out, float value) {

  if (value == 0.0f) {
    out << "0.0f";
    return;
  }

  out << std::setprecision(
             std::numeric_limits<float>::max_digits10);

  out << value;

  // Make sure the literal is explicitly a floating-point literal.
  out << "f";
}

} // namespace

int main(int argc, char **argv) {

  if (argc < 3) {
    std::cerr
        << "Usage: " << argv[0]
        << " <input.model> <output.hpp> [array_name]\n";

    return 1;
  }

  const std::string input_path = argv[1];
  const std::string output_path = argv[2];

  const std::string array_name =
      sanitize_identifier(
          argc >= 4
              ? argv[3]
              : "ROCK_AI_WEIGHTS");

  std::ifstream in(
      input_path,
      std::ios::binary);

  if (!in) {
    std::cerr
        << "Error: could not open '"
        << input_path
        << "'\n";

    return 1;
  }

  Header header{};

  in.read(
      reinterpret_cast<char *>(&header),
      sizeof(Header));

  if (!in) {
    std::cerr
        << "Error: file too short to contain "
           "a valid header\n";

    return 1;
  }

  if (header.magic != EXPECTED_MAGIC) {

    std::cerr
        << "Error: bad magic number (got 0x"
        << std::hex
        << header.magic
        << ", expected 0x"
        << EXPECTED_MAGIC
        << std::dec
        << "). Is this really a "
           "rock_ai.model file?\n";

    return 1;
  }

  if (header.version != EXPECTED_VERSION) {

    std::cerr
        << "Error: unsupported model version "
        << header.version
        << " (this tool understands version "
        << EXPECTED_VERSION
        << ")\n";

    return 1;
  }

  std::vector<float> parameters(
      header.parameter_count);

  in.read(
      reinterpret_cast<char *>(parameters.data()),
      static_cast<std::streamsize>(
          parameters.size() * sizeof(float)));

  if (!in) {

    std::cerr
        << "Error: file ended before all "
        << header.parameter_count
        << " parameters were read - the file "
           "may be truncated or corrupted\n";

    return 1;
  }

  // Make sure there isn't unexpected trailing data.
  in.peek();

  if (!in.eof()) {

    std::cerr
        << "Warning: file has extra trailing data "
           "past the expected parameter count - "
           "continuing anyway, but double check "
           "this is the right .model file.\n";
  }

  std::ofstream out(output_path);

  if (!out) {

    std::cerr
        << "Error: could not open '"
        << output_path
        << "' for writing\n";

    return 1;
  }

  out
      << "// AUTO-GENERATED by model_to_header.cpp - "
         "do not edit by hand.\n";

  out
      << "// Regenerate with:\n";

  out
      << "//   ./model_to_header "
      << input_path
      << " "
      << output_path
      << "\n";

  out
      << "//\n";

  out
      << "// Source model: "
      << input_path
      << "\n";

  out
      << "#pragma once\n\n";

  out
      << "#include <cstdint>\n\n";

  out
      << "// Metadata copied from the model file's "
         "header. Rock OS should\n";

  out
      << "// construct its Embedding with "
      << array_name
      << "_VOCABULARY_SIZE\n";

  out
      << "// and its layer stack with "
      << array_name
      << "_LAYER_COUNT before\n";

  out
      << "// handing this array to something "
         "equivalent to ModelIO::import_weights\n";

  out
      << "// on each component, in the same "
         "embedding -> layers -> classifier\n";

  out
      << "// order ModelIO::load() uses.\n";

  out
      << "inline constexpr uint32_t "
      << array_name
      << "_VOCABULARY_SIZE = "
      << header.vocabulary_size
      << "u;\n";

  out
      << "inline constexpr uint32_t "
      << array_name
      << "_LAYER_COUNT = "
      << header.layer_count
      << "u;\n";

  out
      << "inline constexpr uint32_t "
      << array_name
      << "_PARAMETER_COUNT = "
      << header.parameter_count
      << "u;\n\n";

  out
      << "inline constexpr float "
      << array_name
      << "["
      << array_name
      << "_PARAMETER_COUNT] = {\n";

  constexpr int VALUES_PER_LINE = 8;

  for (std::size_t i = 0;
       i < parameters.size();
       i++) {

    if (i % VALUES_PER_LINE == 0)
      out << "  ";

    write_float_literal(
        out,
        parameters[i]);

    if (i + 1 != parameters.size())
      out << ",";

    if ((i + 1) % VALUES_PER_LINE == 0 ||
        i + 1 == parameters.size()) {

      out << "\n";

    } else {

      out << " ";
    }
  }

  out << "};\n";

  if (!out) {

    std::cerr
        << "Error: failed while writing '"
        << output_path
        << "'\n";

    return 1;
  }

  std::cout
      << "Wrote "
      << header.parameter_count
      << " parameters ("
      << (header.parameter_count * sizeof(float))
      << " bytes as binary, larger as source text) "
         "to '"
      << output_path
      << "'.\n";

  std::cout
      << "Vocabulary size: "
      << header.vocabulary_size
      << "\n";

  std::cout
      << "Layer count: "
      << header.layer_count
      << "\n";

  return 0;
}
